### ISSUE TITLE
D7: Submenu on Demo site shows for Secondary menu

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-drupal#2]
The submenu on the demo site expands on the login screen in an odd way on the demo site's login page: 

![2017-02-16 at 8 51 pm](https://cloud.githubusercontent.com/assets/132864/23052958/52437e02-f48a-11e6-8b9d-4946d9c31b45.png)

**Comment by MichaelCastelbuono** [comment]
@designerbrent I might be wrong in assuming that only the language selector should have a dropdown sub menu. Can you let us know if we need to support sub menus for all items in that menu?

**Comment by designerbrent** [comment]
I would say that for now, we don't support submenus there, aside from the language menu.

But that means we also need to clean up  this item, or add support for submenus, @MichaelCastelbuono

**Comment by MichaelCastelbuono** [comment]
@designerbrent sounds good. I've deployed a fix for this earlier in case that was the solution. [Here's the commit](https://github.com/adventistchurch/alps-drupal/commit/2efd11fc93167054ff909ef95856cf83c354191d). Also here's the dev site in action http://dev-alps-d7.pantheonsite.io/user.

The latest tree in the drupal 7 branch https://github.com/adventistchurch/alps-drupal/tree/drupal-7 has the latest commits (including the starter sub theme folder and files), which you can use to either update the zip you have on the alps site or make a new one. I can make a new tag if you'd like as well.

**Comment by designerbrent** [comment]
Please go ahead and add a new tag to the D7 branch. `beta1.1`

**Comment by MichaelCastelbuono** [comment]
I just added the tag — https://github.com/adventistchurch/alps-drupal/tree/7.x-2.0-beta1.1
