### ISSUE TITLE
Bugs in Mobile

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-drupal#3]
In testing this on mobile view, There are a few issues that come up.

- Out of the box, the logo is missing on the mobile viewport.
- The secondary menu shows on mobile, when it should be hidden. When you hit the menu button, it goes into the menu where it should be, but when you close the menu, it never disappears.

![2017-08-24 at 4 17 pm](https://user-images.githubusercontent.com/132864/29686738-1cf8900a-88e8-11e7-97a3-d319d821e75d.png)

**Comment by MichaelCastelbuono** [comment]
@designerbrent I was unable to reproduce the logo issue, but I did fix the menu bug. I tried on a fresh install, installed the theme, and the logo worked. I tried setting a new horizontal/mobile logo and then removing it and it still works. Would you mind trying to replicate this with the latest code?

**Comment by MichaelCastelbuono** [comment]
@designerbrent I was just able to duplicate. It was a bug with the theme folder name. I'll commit a fix soon.
