### ISSUE TITLE
Update the default logos

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-drupal#4]
The default logos need to be updated to use the following SVGs:

 - Horizontal: `https://github.com/adventistchurch/alps/blob/bede3bb26dc243eb2faf96d6a80e625eab71c70f/source/images/adventist-logo-h-en.svg`
 - Vertical:  `https://github.com/adventistchurch/alps/blob/bede3bb26dc243eb2faf96d6a80e625eab71c70f/source/images/adventist-logo-m.svg`

**Comment by MichaelCastelbuono** [comment]
0c32725 for dupal 8 fix.
